export const events = [
  {
    slug: "2026-chamber-connect-september",
    title: "Chamber CONNECT — September",
    shortTitle: "Chamber CONNECT",
    date: "2026-09-15T11:00:00-04:00",
    endDate: "2026-09-15T12:00:00-04:00",
    dateLabel: "September 15, 2026",
    timeLabel: "11:00 AM–12:00 PM ET",
    location: "Virtual",
    organizer: "Greater Rochester Chamber",
    image: "/events/chamber-connect.png",
    imageAlt: "Chamber CONNECT event identity",
    imageStyle: "dark",
    status: "Attending",
    sourceUrl: "https://my.greaterrochesterchamber.com/calendar/details/chamber-connect-september-1492377",
    summary: "A fast, interactive virtual networking hour for Greater Rochester Chamber members to introduce their work and build useful local connections.",
    why: "Usatii is attending to meet regional operators who need custom software built around the way their organizations actually work.",
    meet: ["Growing service and trade businesses", "Operations and technology leaders", "Organizations replacing disconnected tools with custom software"],
  },
  {
    slug: "2026-us-ukraine-innovation-exchange",
    title: "Rochester TRENDS: U.S.–Ukraine Innovation Exchange",
    shortTitle: "U.S.–Ukraine Innovation Exchange",
    date: "2026-09-21T10:00:00-04:00",
    endDate: "2026-09-21T12:00:00-04:00",
    dateLabel: "September 21, 2026",
    timeLabel: "10:00 AM–12:00 PM ET",
    location: "Greater Rochester Chamber, Rochester, New York",
    organizer: "Greater Rochester Chamber",
    image: "/events/rochester-trends.png",
    imageAlt: "Rochester TRENDS event identity",
    imageStyle: "dark",
    status: "Attending",
    sourceUrl: "https://my.greaterrochesterchamber.com/calendar/Details/rochester-trends-u-s-ukraine-innovation-exchange-1724785",
    summary: "A discussion on moving defense-sector innovation into commercial use, with a focus on drones, robotics, investment, and U.S.–Ukraine collaboration.",
    why: "Usatii is attending to learn where software, commercialization, and operational systems can support resilient technology companies crossing from research into market use.",
    meet: ["Defense and dual-use technology teams", "Commercialization and investment partners", "Drone, robotics, and advanced-industry operators"],
  },
  {
    slug: "2026-ny-smart-i-corridor-opportunity-exchange",
    title: "Rochester TRENDS: NY SMART I-Corridor Opportunity Exchange",
    shortTitle: "NY SMART I-Corridor Opportunity Exchange",
    date: "2026-10-08T08:00:00-04:00",
    endDate: "2026-10-08T12:00:00-04:00",
    dateLabel: "October 8, 2026",
    timeLabel: "8:00 AM–12:00 PM ET",
    location: "The Strong, Rochester, New York",
    organizer: "Greater Rochester Chamber + NY SMART I-Corridor",
    image: "/events/rochester-trends.png",
    imageAlt: "Rochester TRENDS event identity",
    imageStyle: "dark",
    status: "Attending",
    sourceUrl: "https://my.greaterrochesterchamber.com/calendar/details/rochester-trends-ny-smart-i-corridor-opportunity-exchange-1683031",
    summary: "A semiconductor ecosystem exchange connecting Upstate New York businesses with customers, partners, funding, technical support, and workforce resources.",
    why: "Usatii is attending to meet advanced-industry teams that need custom operational software, workflow automation, data infrastructure, and secure internal systems.",
    meet: ["Advanced manufacturers and suppliers", "Semiconductor ecosystem partners", "Engineering, construction, logistics, and workforce teams"],
  },
  {
    slug: "2026-defense-government-contracting-forum",
    title: "6th Annual Defense & Government Contracting Forum and Matchmaker",
    shortTitle: "Defense & Government Contracting Forum",
    date: "2026-10-13T08:00:00-04:00",
    endDate: "2026-10-13T17:00:00-04:00",
    dateLabel: "October 13, 2026",
    timeLabel: "8:00 AM–5:00 PM ET · Registration from 7:00 AM",
    location: "Woodcliff Hotel & Spa, Fairport, New York",
    organizer: "Monroe County Upstate NY APEX Accelerator",
    image: "/events/defense-forum.webp",
    imageAlt: "6th Annual Defense and Government Contracting Forum and Matchmaker event artwork",
    imageStyle: "cover",
    status: "Attending",
    sourceUrl: "https://www.monroeupstatenyapex.org/events/scndb1edf0440q6294sy7l7p87hmnu",
    summary: "An annual forum connecting businesses with government agencies and prime contractors through training, panels, networking, and scheduled matchmaking.",
    why: "Usatii is attending to understand mission and procurement needs firsthand and meet organizations modernizing secure workflows, public-sector operations, and digital service delivery.",
    meet: ["Federal, state, and local agencies", "Prime contractors and teaming partners", "Defense suppliers and public-sector technology teams"],
  },
  {
    slug: "2026-small-business-in-focus-b2b-sales",
    title: "Small Business in Focus: B2B Sales — A Buyer-Centric Approach",
    shortTitle: "B2B Sales: A Buyer-Centric Approach",
    date: "2026-10-27T08:00:00-04:00",
    endDate: "2026-10-27T10:00:00-04:00",
    dateLabel: "October 27, 2026",
    timeLabel: "8:00–10:00 AM ET",
    location: "Golisano Institute for Business & Entrepreneurship, Rochester, New York",
    organizer: "Greater Rochester Chamber",
    image: "/events/small-business-in-focus.png",
    imageAlt: "Small Business in Focus event identity",
    imageStyle: "dark",
    status: "Attending",
    sourceUrl: "https://my.greaterrochesterchamber.com/calendar/Details/small-business-in-focus-b2b-sales-a-buyer-centric-approach-1709478",
    summary: "A practical GrowthX workshop on targeting, outcome-led messaging, high-trust sales conversations, pipeline discipline, and responsible use of AI in B2B sales.",
    why: "Usatii is attending to better understand how B2B teams work so we can build custom software that supports their real operational processes.",
    meet: ["B2B founders and operational leaders", "Teams with complex internal workflows", "Organizations applying AI inside purpose-built software"],
  },
  {
    slug: "2026-chamber-connect-november",
    title: "Chamber CONNECT — November",
    shortTitle: "Chamber CONNECT — November",
    date: "2026-11-10T11:00:00-05:00",
    endDate: "2026-11-10T12:00:00-05:00",
    dateLabel: "November 10, 2026",
    timeLabel: "11:00 AM–12:00 PM ET",
    location: "Virtual",
    organizer: "Greater Rochester Chamber",
    image: "/events/chamber-connect.png",
    imageAlt: "Chamber CONNECT event identity",
    imageStyle: "dark",
    status: "Attending",
    sourceUrl: "https://my.greaterrochesterchamber.com/calendar",
    summary: "A virtual member networking session built for concise introductions, useful follow-up, and new connections across Greater Rochester’s business community.",
    why: "Usatii is attending to meet local companies that need custom software, connected operational systems, and infrastructure they can own.",
    meet: ["Local business owners", "Operations and technology leaders", "Organizations with workflows that off-the-shelf software cannot handle"],
  },
  {
    slug: "2026-chamber-member-orientation",
    title: "Member Orientation & Services Overview — November",
    shortTitle: "Chamber Member Orientation",
    date: "2026-11-17T08:30:00-05:00",
    endDate: "2026-11-17T10:00:00-05:00",
    dateLabel: "November 17, 2026",
    timeLabel: "8:30–10:00 AM ET",
    location: "Greater Rochester Chamber, Rochester, New York",
    organizer: "Greater Rochester Chamber",
    image: "/events/greater-rochester-chamber.png",
    imageAlt: "Greater Rochester Chamber of Commerce logo",
    imageStyle: "light",
    status: "Attending",
    sourceUrl: "https://my.greaterrochesterchamber.com/calendar",
    summary: "An overview of Chamber resources, advocacy, professional development, talent support, visibility opportunities, and ways for members to participate.",
    why: "Usatii is attending to use its Chamber membership more effectively and identify programs, partnerships, and local resources that can create value for clients and collaborators.",
    meet: ["Chamber leaders and member organizations", "Regional service partners", "Companies looking for trusted local collaborators"],
  },
];

export function getEvent(slug) {
  return events.find((event) => event.slug === slug);
}
